environment:
  matrix:
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2022
    QTPATH: C:\Qt\6.5\msvc2019_64
    OpenSSL: C:\OpenSSL-v111-Win64\bin
    OS: win
    EXT: zip
    VCVARSALLPATH: C:\"Program Files\Microsoft Visual Studio"\2022\Community\VC\Auxiliary\Build\vcvars64.bat
    APPVEYOR_RDP_PASSWORD:
        secure: XDOulHbT+GnN6t+WhbRdIlxJThwnVnF5Tj+P7lIc/QA=
  - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu2204
    QTVER: 6.4
    OS: linux
    EXT: tar.gz
    APPVEYOR_SSH_KEY: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCnzgGEneZEeiFacT9D/oYW+LCBIiA8PPgv2i52a0z78Gin8q21WTmDB2xHj3u07MxPPyOVKQIrOGFZkQrKxbhyj9K19RTLq7vEu0Bh3ruEyGaoBmcU5B0LXwLfs4R3y9z+Hi5WNWrOMqYMR01L49oQrPwp9gv/OxDEpnYo05Q1xF2aGBghw2Ar1TihZ/68h1a3/XMaimlUgfU6gydHLDtsOCbiqusCLIJpDfdNzCE0H7Ht3yZa4LflTYk6ICy8gOddllDowmLRkZVKBMidTPfA0zkD+6hN3r0CuCZJZ70TtrFu95UpAYb03SQpMndZcUjyT+F15YNaokCfr/tNI5WdXICJdwOHJ0cu5VbcXEuCaUlOVmgGdRK09ZO2h9fOE6qAmQwV7ao1/AUPwoPVTTta1sRAl1k+J3PEjXU/b/sOndxTNwmlXN9bblUfHnrn1e9ts48NtnaMpyjhL2mnTKEoYlDQWezYQU/crqR31P62YLlNUK7VP5/vIsYP/9H+SmVKRi4gOuOdf3rOMwPDlYbdIPGLJ9SDCHWZyCEkYhAzzxW/zD+KB7KDAy3+MGosaAaBvbPWP7mHquVNX9nvNd4X75mRgq92Cm6SWkIeO47SVDovqP1PiR+K8gy+lYOSxF7vgksHMumJWEh3AMH3IGxLamaAsyKklWSNZ/jhjpFRUQ==
  - APPVEYOR_BUILD_WORKER_IMAGE: macos-monterey
    QTVER: 6.6
    OS: macOS
    EXT: tar.gz
    APPVEYOR_SSH_KEY: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCnzgGEneZEeiFacT9D/oYW+LCBIiA8PPgv2i52a0z78Gin8q21WTmDB2xHj3u07MxPPyOVKQIrOGFZkQrKxbhyj9K19RTLq7vEu0Bh3ruEyGaoBmcU5B0LXwLfs4R3y9z+Hi5WNWrOMqYMR01L49oQrPwp9gv/OxDEpnYo05Q1xF2aGBghw2Ar1TihZ/68h1a3/XMaimlUgfU6gydHLDtsOCbiqusCLIJpDfdNzCE0H7Ht3yZa4LflTYk6ICy8gOddllDowmLRkZVKBMidTPfA0zkD+6hN3r0CuCZJZ70TtrFu95UpAYb03SQpMndZcUjyT+F15YNaokCfr/tNI5WdXICJdwOHJ0cu5VbcXEuCaUlOVmgGdRK09ZO2h9fOE6qAmQwV7ao1/AUPwoPVTTta1sRAl1k+J3PEjXU/b/sOndxTNwmlXN9bblUfHnrn1e9ts48NtnaMpyjhL2mnTKEoYlDQWezYQU/crqR31P62YLlNUK7VP5/vIsYP/9H+SmVKRi4gOuOdf3rOMwPDlYbdIPGLJ9SDCHWZyCEkYhAzzxW/zD+KB7KDAy3+MGosaAaBvbPWP7mHquVNX9nvNd4X75mRgq92Cm6SWkIeO47SVDovqP1PiR+K8gy+lYOSxF7vgksHMumJWEh3AMH3IGxLamaAsyKklWSNZ/jhjpFRUQ==

install:
    - git submodule update --init
    - sh: bash .ci/install.sh

before_build:
    - cmd: set PATH=%QTPATH%\bin;%PATH%
    - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
    - cmd: call %VCVARSALLPATH%

build_script:
    - mkdir build
    - cd build
    - cmd: cmake -G"NMake Makefiles" -DCMAKE_BUILD_TYPE=RELEASE -DTEST=ON ../
    - sh: export APPVEYOR_SSH_BLOCK=true
    - sh: curl -sflL 'https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-ssh.sh' | bash -e -
    - sh: bash ../.ci/build.sh
    - cmake --build . -j 4
    - ctest -V

after_build:
    - cd ..
    - cmd: md PokeFinder-windows
    - cmd: move build\Source\PokeFinder.exe PokeFinder-windows\PokeFinder.exe
    - cmd: windeployqt --no-translations --no-plugins --no-opengl-sw --no-system-d3d-compiler PokeFinder-windows\PokeFinder.exe
    - cmd: del PokeFinder-windows\vc_redist*.exe
    - cmd: xcopy /I %QTPATH%\plugins\platforms\qwindows.dll PokeFinder-windows\platforms\
    - cmd: xcopy /I %QTPATH%\plugins\styles\qwindowsvistastyle.dll PokeFinder-windows\styles\
    - cmd: xcopy /I %OpenSSL%\libcrypto*.dll PokeFinder-windows\
    - cmd: xcopy /I %OpenSSL%\libssl*.dll PokeFinder-windows\
    - cmd: 7z a PokeFinder-win.zip PokeFinder-windows\
    - cmd: sha256sum PokeFinder-win.zip > PokeFinder-win.zip.sha256
    - sh: bash .ci/after_build.sh

artifacts:
- path: PokeFinder-%OS%.%EXT%
- path: PokeFinder-%OS%.%EXT%.sha256

deploy:
    provider: GitHub
    description: ''
    auth_token:
        secure: SFsouaBlVG46u5QjtuDZMhTxq9FHVPr1BRF6YwNJhOtlj+vk707p3MEzHttr7Vep
    artifact: PokeFinder-%OS%.%EXT%,PokeFinder-%OS%.%EXT%.sha256
    on:
        APPVEYOR_REPO_TAG: true
